blog/urls.py
from django.conf.urls import patterns, include, url

from blog.views import TimelineView

urlpatterns = patterns('',
    url(r'^', TimelineView.as_view(), name='timeline'),
)

epirev/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

import debug_toolbar

#import debug_toolbar

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'epirev.views.home', name='home'),
    url(r'^blog/', include('blog.urls', app_name='blog', namespace='blog')),
    url(r'^project/', include('projects.urls', app_name='projects',
        namespace='projects')),
    url(r'^forum/', include('chinwag.urls', app_name='chinwag',
        namespace='chinwag')),

    url(r'^contact/$', 'epirev.views.contact', name='contact'),
    url(r'^team/$', 'epirev.views.team', name='team'),

    url(r'', include('accounts.urls', app_name='accounts',
                     namespace='accounts')),

    url(r'^avatar/', include('avatar.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^__debug__/', include(debug_toolbar.urls)),
)

projects/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from projects.views import ProjectCreate, ProjectUpdate

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^all$', 'projects.views.projects', name='all'),
    url(r'^create$', ProjectCreate.as_view(), name='create'),
    url(r'^update/(?P<slug_name>[\w-]+)', ProjectUpdate.as_view(),
        name='update'),
    url(r'^(?P<slug_name>[\w-]+)$', 'projects.views.project', name='project'),
)

projects/models.py
from django.utils.text import slugify
from django.db import models

from easy_thumbnails.fields import ThumbnailerImageField as ImageField

from epirev.utils import mdrenderer
from chinwag.models import Forum
from epirev.models import View

class Tech(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

class Project(models.Model):
    BOOL_CHOICES = ((True, 'Yes'), (False, 'No'))

    PROJECT_END_CHOICES = (
        ('F', 'Finished'),
        ('D', 'Dropped'),
    )

    name = models.CharField(max_length=50)
    creator = models.ForeignKey('accounts.User')
    slug_name = models.SlugField(unique=True, blank=True, editable=False)
    image = ImageField(upload_to="projects/project/images/",
            default="projects/project/images/default.png")
    short_description = models.TextField()

    description = models.TextField(blank=True, editable=False)
    description_markdown = models.TextField(blank=True)

    members = models.ManyToManyField('accounts.User',
            related_name='project_members')
    tech = models.ForeignKey(Tech, related_name='project_tech')
    opensource = models.BooleanField(default=True, choices=BOOL_CHOICES)
    pub_date = models.DateField('Date created', auto_now_add=True)
    last_update = models.DateTimeField('Last update', auto_now_add=True)

    forum = models.ForeignKey(Forum, related_name='project_forum')

    end = models.CharField(max_length=20, choices=PROJECT_END_CHOICES,
        blank=True, null=True, default=None)
    end_date = models.DateField(blank=True, null=True)
    visible = models.BooleanField(default=False, choices=BOOL_CHOICES)

    views = models.ManyToManyField(View, related_name='project_views')

    __was_end = None
    __was_visible = None

    def __init__(self, *args, **kwargs):
        super(Project, self).__init__(*args, **kwargs)
        self.__was_end = self.end
        self.__was_visible = self.visible

    def save(self, *args, **kwargs):
        if not self.pk:
            self.slug_name = slugify(self.name)
            forum = Forum(name=self.name)
            forum.save()
            self.forum = forum

        if (not self.pk or not self.__was_end) and self.end:
            self.end_date = timezone.now()

        if (not self.pk or self.__was_visible) and not self.visible:
            self.pub_date = timezone.now()

        self.last_update = timezone.now()
        self.description = mdrenderer.render(self.description_markdown)
        super(Project, self).save(*args, **kwargs)
        self.forum.project = self
        self.forum.save()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name', 'pub_date']

projects/forms.py
from django import forms
from django.contrib.admin.widgets import FilteredSelectMultiple

from projects.models import Project
from accounts.models import User

class CreateProjectForm(forms.ModelForm):
    widgets = { 'opensource': forms.RadioSelect, }
    class Meta:
        model = Project
        fields = [
                'name',
                'image',
                'short_description',
                'members',
                'opensource',
                'tech',
                ]

    class Media:
         css = {'all': ('/static/css/multiple-select.css',),}
         js = ('/static/js/jquery.multiple.select.js',)

class UpdateProjectForm(forms.ModelForm):
    widgets = { 'opensource': forms.RadioSelect, }
    class Meta:
        model = Project
        fields = [
                'description_markdown',
                'members',
                'image',
                'name',
                'short_description',
                'opensource',
                'end',
                ]

    class Media:
         css = {'all': ('/static/css/multiple-select.css',),}
         js = ('/static/js/jquery.multiple.select.js',)

projects/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse_lazy, reverse
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic.edit import CreateView, UpdateView
from django import forms
from django.forms.models import modelform_factory
from django.utils import timezone
from django.conf import settings
from django.db.models import Count

from ipware.ip import get_ip

from projects.models import Project
from projects.forms import CreateProjectForm, UpdateProjectForm

def projects(request):
    if request.user.is_authenticated():
        all_projects = Project.objects \
            .annotate(num_views = Count('views')) \
            .select_related('tech') \
            .prefetch_related('members')
    else:
        all_projects = Project.objects \
            .filter(visible=True) \
            .annotate(num_views = Count('views')) \
            .select_related('tech') \
            .prefetch_related('members')

    old_projects = [p for p in all_projects if p.end]

    user_projects = []
    if request.user.is_authenticated():
        user_projects = [p for p in all_projects if not p in old_projects and
                request.user in p.members.all()]

    projects = [p for p in all_projects if not p.end and not p in
            user_projects]

    return render(request, 'projects/projects.html', {
        'projects': projects,
        'old_projects': old_projects,
        'user_projects': user_projects,
    })

def project(request, slug_name):
    try:
        project = Project.objects.prefetch_related('views').get(
                slug_name=slug_name)
    except Project.DoesNotExist:
        raise Http404()

    if not project.visible and not request.user.is_authenticated():
        return redirect('/login/?next=%s' % request.path)

    user = request.user if request.user.is_authenticated() else None
    ip = get_ip(request)
    if ip is not None:
        matched_views = [view for view in project.views.all()
                if view.ip == ip][:1]
        if matched_views:
            elapsed = (timezone.now() - matched_views[0].date).seconds
            if elapsed > settings.PROJECTS_TIME_BETWEEN_VIEWS:
                project.views.create(ip=ip, user=user)
        else:
            project.views.create(ip=ip, user=user)

    return render(request, 'projects/project.html', { 'project': project, })

class ProjectCreate(CreateView):
    model = Project
    template_name = 'projects/create.html'
    success_url = reverse_lazy('projects')
    form_class = CreateProjectForm

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProjectCreate, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.creator = self.request.user
        obj.save()
        return HttpResponseRedirect(self.success_url)

class ProjectUpdate(UpdateView):
    model = Project
    template_name = 'projects/update.html'
    form_class = UpdateProjectForm

    def get_object(self, queryset=None):
        obj = Project.objects.get(slug_name=self.kwargs['slug_name'])
        return obj

    def get_success_url(self):
        return reverse_lazy('projects:project',
                kwargs={'slug_name': self.object.slug_name})

templates/projects/create.html
{% extends "base.html" %}

{% block scripts %}
{{ block.super }}
{{ form.media }}
{% endblock scripts %}

{% block content %}

<form action="{% url 'projects:create' %}" method="post" accept-charset="utf-8"
    class="form" id="project-create-form" enctype="multipart/form-data">
    {% if form.non_field_errors %}
    <p class="form-error">{{ form.non_field_errors }}</p>
    {% endif %}
    <h4 class="form-caption">Create a new project</h4>
    {% csrf_token %}
    <p class="form-field{% if form.name.errors %} error{% endif %}">
        <input type="text" placeholder="Name of the project" name="name"
        autofocus="true"/>
    </p>
    {{ form.name.errors }}
    <label for="id_image">Project image</label>
    <p class="form-field{% if form.image.errors %} error{% endif %}">
        {{ form.image }}
    </p>
    {{ form.image.errors }}
    <label for="id_tech">Technology in use</label>
    <p class="form-field-container{% if form.tech.errors %} error{% endif %}">
        {{ form.tech }}
    </p>
    {{ for.tech.errors }}
    <label for="id_short_description">
        Clear synopsis of what the project is (a few words)
    </label>
    <p class="form-field{% if form.short_description.errors %}
        error{% endif %}">
        {{ form.short_description }}
    </p>
    {{ form.short_description.errors }}
    <label for="id_members">
        Members involved in this project
    </label>
    <p class="form-field-container{% if form.members.errors %}
        error{% endif %}">
        {{ form.members }}
    </p>
    {{ form.members.errors }}
    <label for="id_opensource">
        Opensource?
    </label>
    {{ form.opensource }}
    <p class="form-actions">
        <input type="submit" class="useless" />
        <a class="btn btn-primary"
            onclick="$('#project-create-form').submit();">
            Submit this project (must be validated by an admin)
        </a>
        <a href="{% url 'projects:all' %}" class="btn btn-default">
            List our projects
        </a>
    </p>
    <input type="hidden" name="next" value="{{ next|escape }}" />
</form>
<script type="text/javascript" charset="utf-8">
$(document).ready(function() {
    $('#id_members').multipleSelect({
        position: 'top'
    });
});
</script>

{% endblock content %}

templates/projects/project.html
{% extends "base.html" %}

{% load mathjax %}

{% block scripts %}
{{ block.super }}
{% mathjax_scripts %}
{% endblock scripts %}

{% block content %}

{% url 'projects:update' slug_name=project.slug_name as update_link %}

<h2>
    <a class="return" href="{% url 'projects:all' %}">
        <i class="fa fa-arrow-circle-o-left"></i>
    </a>
    {% load thumbnail %}
    <img class="project-image" src="{% thumbnail project.image 50x50 crop %}">
    {{ project.name }}
    {% if user.is_member %}
    <a class="btn btn-primary edit" href="{{ update_link }}">
        Edit
    </a>
    {% endif %}
</h2>

<div class="markup-container">

{% if project.description %}
{{ project.description|safe }}
{% else %}
<p class="nothing"><em>This project doesn't have a description.</em>
{% if user.is_authenticated and user.is_member %}
You should definitely <a href="{{ update_link }}">provide one</a>.</p>
{% endif %}
{% endif %}

</div>

{% endblock content %}

templates/projects/projects.html
{% extends 'base.html' %}

{% block content %}
{% if projects or old_projects or user_projects %}
{% url 'projects:project' as project_base_url %}
{% if user_projects %}
<h3>
    Your projects <span class="count">{{ user_projects.count }}</span>
</h3>
<div class="projects">
    {% include "projects/projects.render.html" with projects=user_projects %}
</div>
{% endif %}
{% if projects %}
<h3>
    {% if user_projects %}
    Other projects
    {% else %}
    Projects we are currently working on
    {% endif %}
    <span class="count">{{ projects.count }}</span></h3>
<div class="projects">
    {% include "projects/projects.render.html" with projects=projects %}
</div>
{% endif %}
{% if old_projects %}
<h3>Old work
    <span class="count">{{ old_projects.count }}</span></h3>
<div class="projects projects-old">
    {% include "projects/projects.render.html" with projects=old_projects %}
</div>
{% endif %}
{% else %}
<p class="nothing">There is no project. It seems we are doing nothing
for the moment... :(</p>
{% endif %}

{% endblock %}

templates/projects/projects.render.html
{% load humanize %}
{% load thumbnail %}

{% for project in projects %}
<div class="project">
    <img class="logo" src="{% thumbnail project.image 90x90 crop %}"
    width="90px" height="90px">
    <div class="content">
        <h5 class="name">
            <a href="{{ project_base_url|add:project.slug_name }}">
                {{ project.name }}
            </a>
            {% if project.end %}
            {% if project.end == 'D' %}
            <span class="visibility closed">Dropped</span>
            {% else %}
            <span class="visibility open">Finished</span>
            {% endif %}
            {% endif %}
            {% if project.opensource %}
            <span class="visibility open">Open source</span>
            {% else %}
            <span class="visibility closed">Closed source</span>
            {% endif %}
            <span class="views">
                {{ project.num_views }} <i class="fa fa-eye"></i>
            </span>
        </h5>
        <span class="info">
            {{ project.tech }} <span>·</span>
            {% if project.end %}
            {% if project.end == 'D' %}dropped{% else %}finished{% endif %}
            <strong>{{ project.end_date|date_ago }}</strong>
            {% else %}
            started <strong>{{ project.pub_date|date_ago }}</strong>
            {% endif %}
        </span>
        <p class="description">
        {{ project.short_description }}
        </p>
    </div>
</div>
{% endfor %}

templates/projects/update.html
{% extends "base.html" %}

{% block scripts %}
{{ block.super }}
{{ form.media }}
{% endblock scripts %}

{% block content %}

<form action="{% url 'projects:update' slug_name=object.slug_name %}"
    method="post" accept-charset="utf-8" class="form" id="project-create-form"
    enctype="multipart/form-data">
    {% if form.non_field_errors %}
    <p class="form-error">{{ form.non_field_errors }}</p>
    {% endif %}

    <h4 class="form-caption">
        Update project '<em>{{ object.name }}</em>'
        <a class="btn btn-default btn-xs" style="float: right"
            href="{% url 'projects:project' slug_name=object.slug_name %}">
            Come back to project
        </a>
        <a class="btn btn-primary btn-xs" style="float: right"
            onclick="$('#project-create-form').submit();">
            Save
        </a>
    </h4>
    {% csrf_token %}

    <label for="id_description_markdown" class="padtop">
        Project description (explain well please, in markdown)
    </label>
    <p class="form-field{% if form.description_markdown.errors %}
        error{% endif %}">
        {{ form.description_markdown }}
    </p>
    {{ form.description_markdown.errors }}

    <label for="id_members">
        Members involved in this project
    </label>
    <p class="form-field-container{% if form.members.errors %}
        error{% endif %}">
        {{ form.members }}
    </p>
    {{ form.members.errors }}

    <label for="id_short_description">
        Clear synopsis of what the project is (a few words)
    </label>
    <p class="form-field{% if form.short_description.errors %}
        error{% endif %}">
        {{ form.short_description }}
    </p>
    {{ form.short_description.errors }}

    <label for="id_name">
        Project name
    </label>
    <p class="form-field{% if form.name.errors %} error{% endif %}">
        <input type="text" placeholder="Name of the project" name="name"
        value="{{ object.name }}" />
    </p>
    {{ form.name.errors }}

    <label for="id_image">Project image</label>
    <p class="form-field{% if form.image.errors %} error{% endif %}">
        <img src="/media/{{ object.image }}" style="max-width: 100px;
            max-height: 100px;"/>
        <input id="id_image" name="image" type="file" />
    </p>
    {{ form.image.errors }}


    <label for="id_opensource">
        Opensource?
    </label>
    {{ form.opensource }}

    <p class="form-actions">
        <input type="submit" class="useless" />
        <a class="btn btn-primary"
            onclick="$('#project-create-form').submit();">
            Save
        </a>
    </p>
    <input type="hidden" name="next" value="{{ next|escape }}" />
</form>
<script type="text/javascript" charset="utf-8">
$(document).ready(function() {
    $('#id_members').multipleSelect({
        position: 'top'
    });
});
</script>

{% endblock content %}