accounts/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^login/$', 'django.contrib.auth.views.login',
        { 'template_name': 'accounts/login.html' }, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', { 'next_page': '/' },
        name='logout'),
    url(r'^reset/$', 'django.contrib.auth.views.password_reset',
        { 'template_name': 'accounts/reset.html' }, name='password_reset'),
    url(r'^reset/done$', 'django.contrib.auth.views.password_reset_done',
        { 'template_name': 'accounts/reset_done.html' },
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm',
        { 'template_name': 'accounts/reset_confirm.html' },
        name='password_reset_confirm'),
    url(r'^reset/complete$',
        'django.contrib.auth.views.password_reset_complete',
        { 'template_name': 'accounts/reset_complete.html' },
        name='password_reset_complete'),
)

blog/urls.py
from django.conf.urls import patterns, include, url

from blog.views import TimelineView

urlpatterns = patterns('',
    url(r'^', TimelineView.as_view(), name='timeline'),
)

epirev/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

import debug_toolbar

#import debug_toolbar

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'epirev.views.home', name='home'),
    url(r'^blog/', include('blog.urls', app_name='blog', namespace='blog')),
    url(r'^project/', include('projects.urls', app_name='projects',
        namespace='projects')),
    url(r'^forum/', include('chinwag.urls', app_name='chinwag',
        namespace='chinwag')),

    url(r'^contact/$', 'epirev.views.contact', name='contact'),
    url(r'^team/$', 'epirev.views.team', name='team'),

    url(r'', include('accounts.urls', app_name='accounts',
                     namespace='accounts')),

    url(r'^avatar/', include('avatar.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^__debug__/', include(debug_toolbar.urls)),
)

accounts/models.py
from epirev import settings
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

class Title(models.Model):
    name = models.CharField(max_length=18)
    level = models.PositiveSmallIntegerField(default=0)
    color = models.CharField(max_length=10)

    def __str__(self):
        return self.name + ' (' + str(self.level) + ')'

    class Meta:
        ordering = ['-level', 'name']

class UserManager(BaseUserManager):
    def create_user(self, username, email, password):
        if not email:
            raise ValueError('Users must have an email')
        if not username:
            raise ValueError('Users must have an username')

        if not password:
            raise ValueError('Users must have a password')

        user = self.model(
            username=username,
            email=email,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password):
        user = self.create_user(username, email, password=password)
        user.is_admin = True
        user.is_active = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    username = models.CharField(
        verbose_name='username',
        max_length=20,
        unique=True,
    )
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
    )

    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )

    gender = models.CharField(max_length=20, choices=GENDER_CHOICES,
            default='Male')

    first_name = models.CharField(max_length=40, null=True, blank=True)
    last_name = models.CharField(max_length=40, null=True, blank=True)

    joined = models.DateTimeField(auto_now_add=True)

    login_x = models.CharField(max_length=20, unique=True)
    website = models.URLField(blank=True)
    school = models.CharField(max_length=40)
    projects = models.ManyToManyField('projects.Project',
            related_name='project_members', blank=True)

    titles = models.ManyToManyField(Title, blank=True)
    level = models.PositiveSmallIntegerField(default=0)

    follows = models.ManyToManyField('chinwag.Follow', blank=True,
            related_name='user_follows')

    email_follows = models.BooleanField(default=True)
    email_general = models.BooleanField(default=True)

    threads_per_page = models.PositiveSmallIntegerField(
            default=settings.CHINWAG_DEFAULT_THREADS_PER_PAGE)
    posts_per_page = models.PositiveSmallIntegerField(
            default=settings.CHINWAG_DEFAULT_POSTS_PER_PAGE)

    objects = UserManager()

    USERNAME_FIELD = 'username'

    REQUIRED_FIELDS = ['email']

    def save(self, *args, **kwargs):
        if self.pk and len(self.titles.all()) > 0:
            self.level = max(title.level for title in self.titles.all())
        super(User, self).save(*args, **kwargs)

    def get_full_name(self):
        if self.last_name and self.first_name:
            return self.first_name + ' ' + self.last_name
        return self.username

    def get_short_name(self):
        return self.username

    def __str__(self):
        return self.get_full_name()

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        return True

    def is_office(self):
        return self.level > 5

    def is_member(self):
        return self.level > 3

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        return self.is_admin

    class Meta:
        ordering = ['-level', 'first_name', 'username', ]

templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<form action="{% url 'accounts:login' %}" method="post" accept-charset="utf-8"
    id="login-form" class="form">
    {% if form.non_field_errors %}
    <p class="form-error">Wrong username/password. Try again.</p>
    {% endif %}
    <h4 class="form-caption">Log in</h4>
    {% csrf_token %}
    <p class="form-field{% if form.username.errors %} error{% endif %}">
        <input type="text" placeholder="Username" name="username"
        autofocus="true"/>
    </p>
    {{ form.username.errors }}
    <p class="form-field{% if form.password.errors %} error{% endif %}">
        <input type="password" placeholder="Password" name="password"
        autofocus="true"/>
    </p>
    {{ form.password.errors }}
    <p class="form-actions">
        <input type="submit" class="useless" />
        <a class="btn btn-primary" onclick="$('#login-form').submit();">Go!</a>
        <a href="{% url 'accounts:password_reset' %}" class="btn btn-success">
            I forgot my password =(
        </a>
    </p>
    <input type="hidden" name="next" value="{{ next|escape }}" />
</form>
{% endblock content %}

templates/accounts/reset.html
{% extends "base.html" %}

{% block content %}
<form action="{% url 'password_reset' %}" method="post" accept-charset="utf-8"
    id="reset-form" class="form">
    <h4 class="form-caption">Reset your password</h4>
    {% csrf_token %}
    <p class="form-field{% if form.email.errors %} error{% endif %}">
        <input type="text" placeholder="Email address" name="email"
        autofocus="true"/>
    </p>
    {{ form.email.errors }}
    <p class="form-actions">
        <input type="submit" class="useless" />
        <a class="btn btn-primary" onclick="$('#reset-form').submit();">
            Send me an email
        </a>
        <a class="btn btn-default" href="{% url 'login' %}">
            Log in
        </a>
    </p>
    <input type="hidden" name="next" value="{{ next|escape }}" />
</form>
{% endblock content %}

templates/accounts/reset_complete.html
{% extends "base.html" %}

{% block content %}

<div class="message-container">
    <p class="message success">
        <i class="fa fa-check"></i> Password updated! You can now
        <a href="{% url 'login' %}"><strong>log in</strong></a>
    </p>
</div>

{% endblock content %}

templates/accounts/reset_confirm.html
{% extends "base.html" %}

{% block content %}
<form action="." method="post"
    accept-charset="utf-8" id="reset-form" class="form">
    <h4 class="form-caption">Enter a new password</h4>
    {% if form.non_field_errors %}
    <p class="form-errors">{{ form.non_field_errors }}</p>
    {% endif %}
    {% csrf_token %}
    <p class="form-field{% if form.new_password1.errors %} error{% endif %}">
        <input type="password" placeholder="new password" name="new_password1"
        autofocus="true" />
    </p>
    <p class="form-field-errors">
        {{ form.new_password1.errors }}
    </p>
    <p class="form-field{% if form.new_password2.errors %} error{% endif %}">
        <input type="password" placeholder="confirm new password"
        name="new_password2" />
    </p>
    <p class="form-field-errors">
        {{ form.new_password2.errors }}
    </p>
    <p class="form-actions">
        <input type="submit" class="useless" />
        <a class="btn btn-primary" onclick="$('#reset-form').submit();">
            Change password
        </a>
        <a class="btn btn-default" href="{% url 'login' %}">
            Log in
        </a>
    </p>
    <input type="hidden" name="next" value="{{ next|escape }}" />
</form>
{% endblock content %}

templates/accounts/reset_done.html
{% extends "base.html" %}

{% block content %}

<div class="message-container">
    <p class="message success">
        <i class="fa fa-check"></i> Done! If the email you entered was correct
        you should see a message in your mailbox.</br>
        (for security reasons, we don't tell you if the email you gave us is in
        the database)</br>
        Contact us at
        <a href="mailto:help@epirev.com"><strong>help@epirev.com</strong></a>
        if you have any issue.
    </p>
</div>

{% endblock content %}