blog/urls.py
from django.conf.urls import patterns, include, url

from blog.views import TimelineView

urlpatterns = patterns('',
    url(r'^', TimelineView.as_view(), name='timeline'),
)

chinwag/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from chinwag.views import HotView
from chinwag.views import HotAjaxView
from chinwag.views import ForumView
from chinwag.views import ForumAjaxView
from chinwag.views import ThreadView

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^$', HotView.as_view(), name='hot'),
    url(r'^ajax/hot$', HotAjaxView.as_view(), name='hot_ajax'),
    url(r'^ajax/(?P<slug_name>[\w-]+)$', ForumAjaxView.as_view(),
        name='forum_ajax'),
    url(r'^(?P<slug_name>[\w-]+)$', ForumView.as_view(), name='forum'),
    url(r'^(?P<slug_name>[\w-]+)/(?P<slug_subject>[\w-]+)$',
        ThreadView.as_view(), name='thread'),
)

epirev/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

import debug_toolbar

#import debug_toolbar

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'epirev.views.home', name='home'),
    url(r'^blog/', include('blog.urls', app_name='blog', namespace='blog')),
    url(r'^project/', include('projects.urls', app_name='projects',
        namespace='projects')),
    url(r'^forum/', include('chinwag.urls', app_name='chinwag',
        namespace='chinwag')),

    url(r'^contact/$', 'epirev.views.contact', name='contact'),
    url(r'^team/$', 'epirev.views.team', name='team'),

    url(r'', include('accounts.urls', app_name='accounts',
                     namespace='accounts')),

    url(r'^avatar/', include('avatar.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^__debug__/', include(debug_toolbar.urls)),
)

chinwag/models.py
import difflib

from django.utils.text import slugify
from django.db import models

from easy_thumbnails.fields import ThumbnailerImageField as ImageField

from epirev.models import View
from accounts.models import User
from epirev.utils import mdrenderer

class PostEdit(models.Model):
    diff = models.TextField()
    author = models.ForeignKey(User, related_name='post_edit_author')
    date = models.DateTimeField(auto_now_add=True)

class Post(models.Model):
    content = models.TextField('Content')
    markdown = models.TextField('Markdown content')
    author = models.ForeignKey(User, related_name='post_author')
    date = models.DateTimeField('Date posted', auto_now_add=True)
    edits = models.ManyToManyField(PostEdit)
    thread = models.ForeignKey('Thread')

    new = False

    __markdown = None

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.__markdown = self.markdown

    def save(self, *args, **kwargs):
        just_created = not self.pk
        if self.__markdown != self.markdown:
            self.content = mdrenderer.render(self.markdown)
            if not just_created:
                previous = self.__markdown.splitlines(True) if self.__markdown\
                        else ['']
                self.edits.create(
                    diff = difflib.unified_diff(previous,
                        self.markdown.splitlines(True)),
                    author = self.author,
                )
        super(Post, self).save(*args, **kwargs)
        if just_created:
            self.thread.last_post = self
            self.thread.save()

    def delete(self, *args, **kwargs):
        last_post = self.thread.posts.all()[:1]
        self.thread.last_post = last_post[0] if last_post else None
        self.thread.save()
        super(Post, self).delete(*args, **kwargs)

    def __str__(self):
        return '#' + str(self.pk)

    class Meta:
        ordering = ['-date']

# BEGIN THREAD

class Thread(models.Model):
    subject = models.CharField('Subject', max_length=140)
    slug_subject = models.SlugField(max_length=140)

    forum = models.ForeignKey('Forum', related_name='thread_forum')

    author = models.ForeignKey(User, related_name='thread_author')
    date = models.DateTimeField(auto_now_add=True)
    last_post = models.ForeignKey(Post, related_name='thread_last_post',
            null=True)

    posts = models.ManyToManyField(Post, related_name='thread_posts')
    views = models.ManyToManyField(View, related_name='thread_views')

    pinned = models.BooleanField(default=False)
    closed = models.BooleanField(default=False)

    new = False

    def save(self, *args, **kwargs):
        self.slug_subject = slugify(self.subject)
        just_created = not self.pk
        super(Thread, self).save(*args, **kwargs)
        if just_created:
            self.forum.save()

    def delete(self, *args, **kwargs):
        self.forum.save()
        super(Thread, self).delete(*args, **kwargs)

    def __str__(self):
        return self.subject

    class Meta:
        unique_together = ('forum', 'slug_subject')
        ordering = ['-pinned', '-last_post__date', '-date']

class Follow(models.Model):
    user = models.ForeignKey(User)
    thread = models.ForeignKey(Thread)
    canceled = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-thread__last_post__date']

# END THREAD

class Forum(models.Model):
    name = models.CharField(max_length=55)
    slug_name = models.CharField(max_length=55, unique=True)
    threads = models.ManyToManyField(Thread, related_name='forum_threads')
    project = models.ForeignKey('projects.Project', null=True, blank=True,
            related_name='forum_project')

    new = False
    pins = 0

    def save(self, *args, **kwargs):
        self.slug_name = slugify(self.name)
        super(Forum, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-project__end', 'name']

class LastSeen(models.Model):
    user = models.ForeignKey(User)
    forum = models.ForeignKey(Forum)
    thread = models.ForeignKey(Thread)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        index_together = [ ['user', 'forum'], ['user', 'thread'] ]
        ordering = ['-date']

    def __str__(self):
        return '<' + self.user.username + '> ' + str(self.date)

chinwag/views.py
from datetime import datetime

from django.shortcuts import render
from django.views.generic.base import TemplateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.db.models import Max, Sum
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from chinwag.models import Forum, Thread, Post, LastSeen

class ForumsAwareMixin:
    def get_forums(self):
        forums = Forum.objects.all().prefetch_related('project__members',
                'threads', 'threads__last_post', 'threads__author')
        projects_forums = []
        user_projects_forums = []
        other_forums = []
        last_seens = LastSeen.objects.filter(user=self.request.user).values(
                'forum', 'date', 'thread__pk')
        for forum in forums:
            forum.pins = 0
            if forum.threads.count():
                for thread in forum.threads.all():
                    last_seen = next((x for x in last_seens \
                            if x['thread__pk'] == thread.pk), None)
                    if (not last_seen and \
                            thread.last_post.date > self.request.user.joined) \
                            or thread.last_post.date > last_seen['date']:
                        forum.pins += 1
            if forum.project:
                if self.request.user in forum.project.members.all() and not \
                        forum.project.end:
                    user_projects_forums.append(forum)
                else:
                    projects_forums.append(forum)
            else:
                other_forums.append(forum)
        projects_forums = user_projects_forums + projects_forums
        return (projects_forums, other_forums)

    def get_context_data(self, **kwargs):
        ctx = super(ForumsAwareMixin, self).get_context_data(**kwargs)
        projects_forums, other_forums = self.get_forums()
        ctx['projects_forums'] = projects_forums
        ctx['other_forums'] = other_forums
        return ctx

class HotViewMixin(TemplateView):
    model = Thread

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(HotViewMixin, self).dispatch(*args, **kwargs)

    def get_hot_threads(self):
        threads = []
        last_seens = LastSeen.objects.filter(user=self.request.user).values(
                'forum', 'date', 'thread')
        for follow in self.request.user.follows \
                .filter(canceled=False) \
                .select_related('thread', 'thread__last_post',
                                'thread__author', 'thread__forum',
                                'thread__last_post__author')[:10]:
            thread = follow.thread
            candidats = [x for x in last_seens if x['thread'] == thread.pk]
            if not candidats or thread.last_post.date > candidats[0]['date']:
                thread.new = True
            threads.append(thread)
        return threads

    def get_context_data(self, **kwargs):
        ctx = super(HotViewMixin, self).get_context_data(**kwargs)
        threads = self.get_hot_threads()
        ctx['threads'] = threads
        return ctx

class HotView(ForumsAwareMixin, HotViewMixin):
    template_name = 'chinwag/forum.html'

    def get_context_data(self, **kwargs):
        ctx = super(HotView, self).get_context_data(**kwargs)
        return ctx

class HotAjaxView(HotViewMixin):
    template_name = 'chinwag/forum.render.html'

    def get_context_data(self, **kwargs):
        ctx = super(HotAjaxView, self).get_context_data(**kwargs)
        return ctx

class ForumViewMixin(TemplateView):
    model = Thread

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ForumViewMixin, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = super(ForumViewMixin, self).get_context_data(**kwargs)
        forum = Forum.objects.get(slug_name=kwargs['slug_name'])
        thread_list = Thread.objects \
            .filter(forum=forum) \
            .select_related('last_post', 'last_post__author') \
            .prefetch_related('views')
        paginator = Paginator(thread_list, 10)
        page = self.request.GET.get('page')
        try:
            threads = paginator.page(page)
        except PageNotAnInteger:
            threads = paginator.page(1)
        except EmptyPage:
            threads = paginator.page(paginator.num_pages)
        last_seens = LastSeen \
            .objects.filter(user = self.request.user, forum = forum) \
            .select_related('thread') \
            .values('thread', 'date')
        for thread in threads:
            last_seen = next((x for x in last_seens if \
                    x['thread'] == thread.pk), None)
            if not last_seen or thread.last_post.date > last_seen['date']:
                thread.new = True
        ctx['threads'] = threads
        ctx['current_forum'] = forum
        return ctx

class ForumView(ForumsAwareMixin, ForumViewMixin):
    template_name = 'chinwag/forum.html'

    def get_context_data(self, **kwargs):
        ctx = super(ForumView, self).get_context_data(**kwargs)
        return ctx

class ForumAjaxView(ForumViewMixin):
    template_name = 'chinwag/forum.render.html'

    def get_context_data(self, **kwargs):
        ctx = super(ForumAjaxView, self).get_context_data(**kwargs)
        return ctx

class ThreadView(ForumsAwareMixin, TemplateView):
    model = Thread
    template_name = 'chinwag/thread.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ThreadView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):

        # Getting the thread and its related data
        # comprising the thread posts (what's of interest here)
        thread = Thread.objects \
            .select_related('forum') \
            .prefetch_related('posts', 'posts__author') \
            .get(slug_subject=kwargs['slug_subject'], \
                 forum__slug_name=kwargs['slug_name'])

        now = timezone.now()

        # Getting the date the user was seen watching this thread for the last
        # time. If she never watched it before, we save a new LastSeen object
        try:
            last_seen = LastSeen.objects.get(user=self.request.user,
                    thread=thread)
        except LastSeen.DoesNotExist:
            last_seen = LastSeen(
                user = self.request.user,
                forum = thread.forum,
                thread = thread,
                date = now,
            )

        # Paginating the thread's posts
        posts_list = thread.posts.all()
        paginator = Paginator(posts_list, self.request.user.posts_per_page)
        page = self.request.GET.get('page')
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            posts = paginator.page(1)
        except EmptyPage:
            posts = paginator.page(paginator.num_pages)

        # Marking the posts as new if the user never saw them
        for post in posts:
            if last_seen.date == now or post.date > last_seen.date:
                post.new = True

        # Updating the last seen date no matter what
        last_seen.date = now
        last_seen.save()

        # This will get the
        ctx = super(ThreadView, self).get_context_data(**kwargs)
        ctx['thread'] = thread
        ctx['current_forum'] = thread.forum
        return ctx

templates/chinwag/base.html
{% extends "base.html" %}

{% block content %}

<table border="0" cellspacing="0" cellpadding="0" id="chinwag">
    <tr>
        <td id="chinwag-nav">
            {% include "chinwag/nav.html" %}
        </td>
        <td id="chinwag-content">
            {% block chinwag-content %}
            threads
            {% endblock chinwag-content %}
        </td>
    </tr>
</table>

{% endblock content %}

templates/chinwag/forum.html
{% extends "chinwag/base.html" %}

{% block chinwag-content %}

<div id="forum-ajax">
{% include "chinwag/forum.render.html" %}
</div>

{% endblock chinwag-content %}

templates/chinwag/forum.render.html
{% load humanize %}

{% if threads.paginator and threads.paginator.num_pages > 1 %}
{% url 'chinwag:forum_ajax' slug_name=slug_name as base_url %}
<div class="pagination">
    <span class="step-links">
        {% if threads.has_previous %}
            <a href="?page={{ threads.previous_page_number }}"
                data="{{ base_url }}?page={{ threads.previous_page_number }}"
                class="forum-ajax-trigger">
                previous
            </a>
        {% endif %}

        <span class="current">
            Page {{ threads.number }} of {{ threads.paginator.num_pages }}
        </span>

        {% if threads.has_next %}
            <a href="?page={{ threads.next_page_number }}"
                data="{{ base_url }}?page={{ threads.next_page_number }}"
                class="forum-ajax-trigger">
                next
            </a>
        {% endif %}
    </span>
</div>
{% endif %}

<table border="0" cellspacing="0" cellpadding="0" class="forum-threads">
    {% for thread in threads %}
    <tr class="forum-thread{% if thread.new %} new{% endif %}">
        <td class="forum-thread-icon">
            {% if thread.pinned %}
            <i class="fa fa-fw fa-thumb-tack"></i>
            {% else %}
                {% if thread.closed %}
                    <i class="fa fa-fw fa-lock"></i>
                {% else %}
                    {% if thread.new %}
                    <i class="fa fa-fw fa-circle"></i>
                    {% else %}
                    <i class="fa fa-fw fa-circle-o"></i>
                    {% endif %}
                {% endif %}
            {% endif %}
        </td>
        <td class="forum-thread-info">
            <span class="subject">
                <a href="{% url 'chinwag:thread' slug_name=thread.forum.slug_name slug_subject=thread.slug_subject %}">
                    {{ thread.subject }}
                </a>
            </span><br>
            <span class="info">
                Last post by
                <a href="">
                    {{ thread.last_post.author.username }}
                </a>
                <strong title="{{ thread.date }}">
                    {{ thread.last_post.date|datetime_ago }}
                </strong>
                · Opened by <a href="">{{ thread.author.username }}</a>
                <strong title="{{ thread.date }}">
                    {{ thread.date|datetime_ago }}
                </strong>
            </span>
        </td>
        <td class="forum-thread-id">
            #{{ thread.pk }}
        </td>
    </tr>
    {% endfor %}
</table>

templates/chinwag/hot.html
{% extends "chinwag/base.html" %}


{% block chinwag-content %}

{% include "chinwag/forum.render.html" %}

{% endblock chinwag-content %}

templates/chinwag/nav.html
<ul>
    <li class="item{% if view_name == 'hot' %} active{% endif %}">
        <a href="{% url 'chinwag:hot' %}" data="{% url 'chinwag:hot_ajax' %}"
            class="forum-ajax-trigger">
            <i class="fa fa-bell-o fa-fw"></i>
            Hot for you {{ request.resolver_match.url_name }}
        </a>
    </li>
    <li class="category">Projects</li>
    {% for forum in projects_forums %}
    <li class="item{% if current_forum == forum %} active{% endif %}">
        <a href="{% url 'chinwag:forum' slug_name=forum.slug_name %}"
            data="{% url 'chinwag:forum_ajax' slug_name=forum.slug_name %}"
            class="forum-ajax-trigger">
            <span class="name">{{ forum.name }}</span>
            {% if forum.pins > 0 %}
            <span class="pin">{{ forum.pins }}</span>
            {% endif %}
            <span class="clear"></span>
        </a>
    </li>
    {% endfor %}
    <li class="category">General</li>
    {% for forum in other_forums %}
    <li class="item{% if current_forum == forum %} active{% endif %}">
        <a href="{% url 'chinwag:forum' slug_name=forum.slug_name %}"
            data="{% url 'chinwag:forum_ajax' slug_name=forum.slug_name %}"
            class="forum-ajax-trigger">
            <span class="name">{{ forum.name }}</span>
            {% if forum.pins > 0 %}
            <span class="pin">{{ forum.pins }}</span>
            {% endif %}
            <span class="clear"></span>
        </a>
    </li>
    {% endfor %}
</ul>

templates/chinwag/thread.html
{% extends "base.html" %}

{% block content %}

{% load avatar_tags %}

<div id="forum-ajax">
  <h1>
  {{ thread.subject }}
  </h1>
  <div id="forum-posts">
    {% for post in thread.posts.all %}
    <p>
      <h3>{{ post.author.get_short_name }}</h3>
      <img class="avatar" src="{% avatar_url post.author 120 %}"
                          alt="{{ post.author.username }}" width="120px"
                          height="120px"/>
      {{ post.content }}
    </p>
    {% endfor %}
  </div>
</div>

{% endblock content %}