accounts/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^login/$', 'django.contrib.auth.views.login',
        { 'template_name': 'accounts/login.html' }, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', { 'next_page': '/' },
        name='logout'),
    url(r'^reset/$', 'django.contrib.auth.views.password_reset',
        { 'template_name': 'accounts/reset.html' }, name='password_reset'),
    url(r'^reset/done$', 'django.contrib.auth.views.password_reset_done',
        { 'template_name': 'accounts/reset_done.html' },
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm',
        { 'template_name': 'accounts/reset_confirm.html' },
        name='password_reset_confirm'),
    url(r'^reset/complete$',
        'django.contrib.auth.views.password_reset_complete',
        { 'template_name': 'accounts/reset_complete.html' },
        name='password_reset_complete'),
)

blog/urls.py
from django.conf.urls import patterns, include, url

from blog.views import TimelineView

urlpatterns = patterns('',
    url(r'^', TimelineView.as_view(), name='timeline'),
)

chinwag/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from chinwag.views import HotView
from chinwag.views import HotAjaxView
from chinwag.views import ForumView
from chinwag.views import ForumAjaxView
from chinwag.views import ThreadView

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^$', HotView.as_view(), name='hot'),
    url(r'^ajax/hot$', HotAjaxView.as_view(), name='hot_ajax'),
    url(r'^ajax/(?P<slug_name>[\w-]+)$', ForumAjaxView.as_view(),
        name='forum_ajax'),
    url(r'^(?P<slug_name>[\w-]+)$', ForumView.as_view(), name='forum'),
    url(r'^(?P<slug_name>[\w-]+)/(?P<slug_subject>[\w-]+)$',
        ThreadView.as_view(), name='thread'),
)

epirev/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

import debug_toolbar

#import debug_toolbar

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'epirev.views.home', name='home'),
    url(r'^blog/', include('blog.urls', app_name='blog', namespace='blog')),
    url(r'^project/', include('projects.urls', app_name='projects',
        namespace='projects')),
    url(r'^forum/', include('chinwag.urls', app_name='chinwag',
        namespace='chinwag')),

    url(r'^contact/$', 'epirev.views.contact', name='contact'),
    url(r'^team/$', 'epirev.views.team', name='team'),

    url(r'', include('accounts.urls', app_name='accounts',
                     namespace='accounts')),

    url(r'^avatar/', include('avatar.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^__debug__/', include(debug_toolbar.urls)),
)

projects/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from projects.views import ProjectCreate, ProjectUpdate

admin.autodiscover()

urlpatterns = patterns('',

    url(r'^all$', 'projects.views.projects', name='all'),
    url(r'^create$', ProjectCreate.as_view(), name='create'),
    url(r'^update/(?P<slug_name>[\w-]+)', ProjectUpdate.as_view(),
        name='update'),
    url(r'^(?P<slug_name>[\w-]+)$', 'projects.views.project', name='project'),
)

templates/base.html
<!doctype html>
<html lang="en">
<head>
<META NAME="ROBOTS" CONTENT="INDEX, FOLLOW">
<meta charset="UTF-8">
<meta http-equiv="content-type" content="text/html;charset=UTF-8">
<title>EPIREV</title>
<meta name="description"
content="Virtual Reality student Association of EPITA">
{% block stylesheet %}
<link rel="stylesheet" href="/static/css/fonts.css">
<link rel="stylesheet" href="/static/css/style.css">
<link rel="stylesheet" href="/static/css/stuff.css">
<link rel="stylesheet" href="/static/css/font-awesome.min.css">
{% endblock stylesheet %}
{% block scripts %}
<script type="text/javascript" src="/static/js/jq.js"></script>
<script type="text/javascript" src="/static/js/nav.js"></script>
<script src="/static/js/forms.js" type="text/javascript" charset="utf-8">
</script>
{% endblock scripts %}
</head>
<body>
<div id="container">
    <header style="background-image: url(/static/img/header-bg.jpg);"
      {% if user.is_authenticated %}class="authenticated"{% endif %}>
        <div id="header">
            <div id="text">
                <a href="{% url 'home' %}" id="logo">
                    epi<span>rev</span>
                </a>
                {% if not user.is_authenticated %}
                <span id="subtitle">
                    Virtual Reality student Association of
                    <strong>EPITA</strong>
                </span>
                <ul id="actions">
                    <li>
                    <a href="{% url 'accounts:login' %}">
                            <span>Team</span> Log in
                        </a>
                    </li>
                    <li><a href="">Join us</a></li>
                </ul>
                {% endif %}
            </div>
        </div>
    </header>
    {% include "nav.html" %}
    <div id="content">
        {% block content %}{% endblock %}
    </div>
    <footer>
        <div class="content">
            <div id="twod"></div>
            <span class="left">
                designed with<img src="/static/img/django.png">by
                <a href="http://too.gy" target="_blank">toogy</a>
                {% if user.is_authenticated and user.is_staff %}
                (<a href="/admin/" target="_blank">administration</a>)
                {% endif %}
            </span>
            <span class="right">
                <img src="/static/img/epita.png">
            </span>
        </div>
    </footer>
</div>
</body>
</html>

templates/nav.html
<nav id="main-nav" class="{% if user.is_authenticated %}logged-in{% endif %}">
    <ul>
        <li>
            <a{% if app_name == 'blog' %} class="active"{% endif %}
                href="{% url 'blog:timeline' %}">
                Blog
            </a>
        </li>
        <li>
            <a{% if app_name == 'projects' %} class="active"{% endif %}
                href="{% url 'projects:all' %}">
                Projects
            </a>
        </li>
        <li>
            <a{% if view_name == 'team' %} class="active"{% endif %}
                href="{% url 'team' %}">
                Team
            </a>
        </li>
        {% if user.is_authenticated %}
        <li>
            <a href="{% url 'chinwag:hot' %}"
                {% if app_name == 'chinwag' %}class="active"{% endif %}
                >
                <i class="fa fa-comments"></i> Forums
            </a>
        </li>
        <li id="user">
            {% load avatar_tags %}
            <a href=""
                {% if app_name == 'accounts' %}class="active"{% endif %}>
                <img src="{% avatar_url user 26 %}" class="avatar" />
                {{ user.username }}
            </a>
        </li>
        <li>
        <a href="{% url 'accounts:logout' %}">
                <i class="fa fa-sign-out fa-fw"></i>
            </a>
        </li>
        {% else %}
        <li>
            <a href="https://bitbucket.org/epirev/" target="_blank">
                <i class="fa fa-bitbucket"></i> Bitbucket
            </a>
        </li>
        <li>
            <a{% if view_name == 'contact' %} class="active"{% endif %}
                href="{% url 'contact' %}">
                Contact us
            </a>
        </li>
        {% endif %}
    </ul>
</nav>

{% if user.is_authenticated %}
<nav id="user-nav">
    <ul>
        {% ifequal app_name 'projects' %}
        <li>
            <a href="{% url 'projects:all' %}"
                {% if view_name == 'all' %} class="active"{% endif %}>
                All projects
            </a>
        </li>
        <li>
            <a href="{% url 'projects:create' %}"
                {% if view_name == 'create' %}class="active"{% endif %}>
                Create a new project
            </a>
        </li>
        {% endifequal %}
    </ul>
</nav>
{% endif %}